### ISSUE TITLE
Purpose of the precision argument in `clock_time_get`

### ISSUE THREAD

**Issue by sunfishcode** [NuxiNL/cloudabi#15]
`clock_time_get` has a `precision` parameter, which has this documentation:

> The maximum lag (exclusive) that the returned
> time value may have, compared to its actual
> value.

The CloudABI implementations on FreeBSD, Linux, and the emulator don't seem to use this parameter.

One hypothetical use for it might be to allow implementations to return an error in case they can't provide the requested level of precision, however in cloudlibc, `clock_time_get`'s return value is usually ignored. And applications can use `clock_res_get` to learn about the precision they're getting from `clock_time_get`.

Is there an expected future use for the `precision` parameter?

**Comment by EdSchouten** [comment]
Hi Dan,

Yes. There is some expected future use for this parameter. You see that some operating systems have all sorts of custom clock sources to specify the desired precision of the timestamp to be obtained. From FreeBSD's `<sys/time.h>`:

```
#define CLOCK_REALTIME  0
#define CLOCK_VIRTUAL   1
#define CLOCK_PROF      2
#define CLOCK_MONOTONIC 4
#define CLOCK_UPTIME    5               /* FreeBSD-specific. */
#define CLOCK_UPTIME_PRECISE    7       /* FreeBSD-specific. */
#define CLOCK_UPTIME_FAST       8       /* FreeBSD-specific. */
#define CLOCK_REALTIME_PRECISE  9       /* FreeBSD-specific. */
#define CLOCK_REALTIME_FAST     10      /* FreeBSD-specific. */
#define CLOCK_MONOTONIC_PRECISE 11      /* FreeBSD-specific. */
#define CLOCK_MONOTONIC_FAST    12      /* FreeBSD-specific. */
#define CLOCK_SECOND    13              /* FreeBSD-specific. */
#define CLOCK_THREAD_CPUTIME_ID 14
#define CLOCK_PROCESS_CPUTIME_ID        15
```

For example, libc's `time()` may use `CLOCK_SECOND`. Using this clock source tends to be faster than using `CLOCK_REALTIME`, as the former uses some cached value. The latter accesses some hardware timer.

The idea behind `precision` is that instead of having a cross product of clock sources (type * precision), an application simply communicates how much imprecision in nanoseconds is tolerated. The runtime/kernel can then pick the proper clock source based on that.

**Comment by sunfishcode** [comment]
Ah, makes sense, thanks!
