### ISSUE TITLE
Is CloudABI versioned in any way?

### ISSUE THREAD

**Issue by jeking3** [NuxiNL/cloudabi#3]
I'm assuming that at some point a syscall might need to be added, and one might need preprocessor definitions to understand which version of CloudABI is available.

Can the ABI version be determined by a preprocessor definition?

Right now all I am finding is `__CloudABI__` which is set to the value of `1`:

```
$ /usr/bin/x86_64-unknown-cloudabi-cc -dM -E - < /dev/null | grep -i abi
#define __CloudABI__ 1
...
```

**Comment by EdSchouten** [comment]
That sounds like a good idea. CCing @m-ou-se, as he wrote the generation scripts initially.

Maurice, would it make sense to just have some `enum` declarations in `cloudabi.txt` to indicate the minor/major version, or should we add a special directive?

**Comment by m-ou-se** [comment]
Let's not use `enum` for these kind of constants: It works fine for C, but the results would be a bit weird when generating code for other languages. Maybe just add a global `version` field. (Or maybe one per syscall?)

**Comment by EdSchouten** [comment]
Maurice and I had a chat on IRC about this topic a bit more, exploring the problem a bit more.

Having a version for the ABI makes sense, but only in terms of release management, documentation purposes, etc. For coding/programmatic access, it however does not buy us much. Providers (kernels, emulators) and consumers (cloudlibc) of this interface will be tied against one specific version of cloudabi. There should be no need to let these support multiple versions, or at least not yet.

As the original intent of this issue was to add version information to Boost, which has in the meantime been fulfilled by using cloudlibc's version number, let's close this issue for the time being. This decision should of course be revisited if conditions change.
